enum Actions {
  CHANGE_MAIN_CONTENTS_MODE_TO_MAIN,
  CHANGE_MAIN_CONTENTS_MODE_TO_GENRE,
  CHANGE_MAIN_CONTENTS_MODE_TO_MYLIST,
  CHANGE_MAIN_CONTENTS_MODE_TO_SEARCH,
  SET_API_ENTRACE_CODE,
  SET_TRACK_LIST,
  SET_SEARCH_RESULT,
  SET_SEARCH_ENTER_ACTIVATED,
  SET_ACCEES_TOKEN_NOW,
  SET_MYLIST_ID,
  SET_PLAYING_NOW_LIST_ID,
  SET_ADD_MUSIC_TO_MYLIST,
  SET_SUB_MUSIC_FROM_MYLIST,
  CHOICE_MUSIC_GENRE,
  CHOICE_PLAY_MUSIC_NOW,
}

export default Actions;
