enum Actions {
  CHANGE_MAIN_CONTENTS_MODE_TO_MAIN,
  CHANGE_MAIN_CONTENTS_MODE_TO_GENRE,
  CHANGE_MAIN_CONTENTS_MODE_TO_SEARCH,
  SET_API_ENTRACE_CODE,
  SET_TRACK_LIST,
  SET_SEARCH_RESULT,
  SET_SEARCH_ENTER_ACTIVATED,
  SET_ACCEES_TOKEN_NOW,
  CHOICE_MUSIC_GENRE,
}

export default Actions;
